name: Checks

#This is the trigger
# on: [push]

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    name: GoTest
    runs-on: macOS-11
    steps:

      - uses: actions/checkout@v1
      # - name: List avaible Xcode ver.
      #   run: ls /Application | grep Xcode

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Run unit tests
        run: xcodebuild clean test -scheme TestGithubActionWithFastlane -project TestGithubActionWithFastlane.xcodeproj 
              -destination 'platform=iOS Simulator, id=94C6DB49-D0D1-45D5-B189-391DFA76BD7D, OS=15.2, name=iPhone 12' | xcpretty && exit ${PIPESTATUS[0]}



  # steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2

    # - name: Cancel Previous Runs
    #     uses: styfle/cancel-workflow-action@0.9.1
    #     with:
    #       access_token: ${{ github.token }}

    # - uses: maxim-lobanov/setup-xcode@v1
    #   with:
    #     xcode-version: latest-stable

    # - uses: ruby/setup-ruby@v1

    # - name: Install Bundler
    #   run: gem install bundler

    # - name: Install gems
    #   run: bundle install

    # - name: Swift Packages Cache
    #   uses: actions/cache@v2
    #   id: cache
    #   with:
    #     path: |
    #       Build/SourcePackages
    #       Build/Build/Products
    #     key: ${{ runner.os }}-deps-v1-${{ hashFiles('BILDsolid.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
    #     restore-keys: ${{ runner.os }}-deps-v1-
    